export const GET_INDICATORS = 'GET_INDICATORS'
export const GET_INDICATORS_SUCCESS = 'GET_INDICATORS_SUCCESS'
export const GET_INDICATORS_ERROR = 'GET_INDICATORS_ERROR'

export const GET_INDICATOR = 'GET_INDICATOR'
export const GET_INDICATOR_SUCCESS = 'GET_INDICATOR_SUCCESS'
export const GET_INDICATOR_ERROR = 'GET_INDICATOR_ERROR'
